name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    uses: ./.github/workflows/release-action.yml
    with:
      publish: true
    permissions:
      contents: write
      id-token: write
