name: Publish Any Commit
# on: [push, pull_request]
on:
  workflow_dispatch:

permissions: {}

jobs:
  release:
    uses: sxzz/workflows/.github/workflows/release-commit.yml@v1
    with:
      compact: true
